# =============================================
#  PORT de l'application (notion DevOps clé !)
# =============================================
server.port=8080

# =============================================
#  CONNEXION À POSTGRESQL (port 5432 par défaut)
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5433/devops_demo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================
#  JPA / HIBERNATE
# =============================================
# create-drop : recrée la table à chaque démarrage (pratique en dev)
# update     : met à jour sans supprimer les données
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =============================================
#  LOGS
# =============================================
logging.level.com.devops=DEBUG
logging.level.org.springframework.web=INFO
