# =============================================
# PORT APPLICATION
# =============================================
server.port=8080

# =============================================
# H2 DATABASE (IN-MEMORY)
# =============================================
spring.datasource.url=jdbc:h2:mem:devops_demo
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =============================================
# CONSOLE H2
# =============================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =============================================
# JPA / HIBERNATE
# =============================================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# create-drop = recrée à chaque démarrage
spring.jpa.hibernate.ddl-auto=create-drop

# affichage SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =============================================
# LOGS
# =============================================
logging.level.com.devops=DEBUG
logging.level.org.springframework.web=INFO